[package]
name = "pixel-art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
draw-prim = { path = "draw-prim" }
image = "0.23.14"
